version: '3'

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: qualidade_apache
    volumes:
      - .:/var/www/html/
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '8080:80'
    networks:
      - qualidadeHP
    environment:
      TZ: "America/Maceio"
  mysql:
    container_name: qualidade_mysql
    image: mysql:latest
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Qualidade@HP!#
      MYSQL_DATABASE: qualidadeHP
      MYSQL_PASSWORD: 123456
      TZ: "America/Maceio"
    ports:
      - '5200:3306'
    networks:
      - qualidadeHP
networks:
  qualidadeHP:
    driver: bridge
